{{- if .Values.api.openai.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "private-rag-poc.fullname" . }}-openai
type: Opaque
data:
  api-key: {{ .Values.api.openai.apiKey | b64enc | quote }}
{{- end }}
