apiVersion: v1
kind: Service
metadata:
  name: {{ include "private-rag-poc.fullname" . }}-ollama
  labels:
    app.kubernetes.io/name: {{ include "private-rag-poc.name" . }}
    app.kubernetes.io/component: ollama
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.ollama.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "private-rag-poc.name" . }}
    app.kubernetes.io/component: ollama
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.ollama.service.port }}
      targetPort: 11434
      protocol: TCP
