apiVersion: v1
kind: Service
metadata:
  name: {{ include "private-rag-poc.fullname" . }}-qdrant
  labels:
    app.kubernetes.io/name: {{ include "private-rag-poc.name" . }}
    app.kubernetes.io/component: qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.qdrant.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "private-rag-poc.name" . }}
    app.kubernetes.io/component: qdrant
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.qdrant.service.port }}
      targetPort: 6333
      protocol: TCP
