apiVersion: v1
kind: Service
metadata:
  name: {{ include "private-rag-poc.fullname" . }}-postgres
  labels:
    app.kubernetes.io/name: {{ include "private-rag-poc.name" . }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.postgres.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "private-rag-poc.name" . }}
    app.kubernetes.io/component: postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: 5432
      protocol: TCP
